### ISSUE TITLE
[FEATURE REQUEST] Better nvidia ShieldTV / AndroidTV support

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [codefaktor/FTVLaunchX#2]
Nice project!

I just sideload it to my (foster) nvidia ShieldTV pro 2015 device (the one with hdd in it) and it works.
But there are some points:

- I can no longer used the double-press one home to see my other opened apps

- I can not use the "menu + home" button option just because shield users normally (there is a brand new remote) does have this menu button on the physical remote

- The listed apps are not all. Would be nice if a user can choose of all apps. Like system settings and so one. Could be useful. And did you know the app "Activity Launcher". See here https://apkcombo.com/de-de/activity-launcher/de.szalkowski.activitylauncher/
With this help to launch custom intent we could do a lot more, I think so. For example with this you can start your fav. netflix movie or show:
https://stackoverflow.com/questions/35556634/movie-deeplink-for-netflix-android-tv-app-com-netflix-ninja

- Is there no chance on AndroidTV to ask o the device to grant the WRITE_SECURE_SETTINGS permission?

- Did you ever think about to add more options. Like to give the user the chance to choose which buttons do what. For example I would love to use the mic-button on my remote for the custom-app. Then my home, back buttons have the shield-standard behavior.

THX for your nice app and your mentioned love to shieldtv users ;-)

**Comment by ErikAbele** [comment]
Since I don't have a ShieldTV, I won't be able to fix this – I'm sorry.
