### ISSUE TITLE
HDMI-CEC Home event takes me back to the Amazon home screen

### ISSUE THREAD

**Issue by bbsuh** [codefaktor/FTVLaunchX#3]
**Issue**
HDMI-CEC Home event takes me back to the Amazon home screen.

**Context**
I like to use my TV's remote control to help manage all devices which is why I have the HDMI CEC functionality enabled. This allows me to not need to use my separate default Amazon Fire Stick remote.

The problem is that pressing the Home button on the TV remote results in going to the default home screen rather than the one selected in FTVLauncherX. 

**Steps to Reproduce**
1. I'm using a Sony TV, but as long as it permits HDMI-CEC it should work. Hook up your TV via HDMI cable. 
2. Go to Settings > Displays & Sounds
3. Enable HDMI CEC Device Control
4. Confirm that it's working, by pressing the directional buttons on your TV
5. Set up FTVLauncherX by installing the APK, and connect to ADB and run `pm grant de.codefaktor.ftvlaunchx android.permission.WRITE_SECURE_SETTINGS`
6. Install something like LeanbackLauncher and link it to FTVLauncherX
7. Press the Home button on the Amazon Fire -- assert that it goes to the LeanbackLauncher indicating that it's working fine.
8. Press the Home button on your TV remote

**Actual Results**
Pressing Home on the TV remote goes back to the Amazon Fire Stick's home screen.

**Expected Results**
Pressing Home on the TV remote goes to the selected FTVLauncherX home screen.

Thanks for your consideration!

**Comment by ErikAbele** [comment]
I was able to test this on my TV set with the remote that came with it and it does work for me when switching on the TV (it takes about 1-2 seconds but it works). Maybe it is some other CEC command Sony is using?
