### ISSUE TITLE
FTVLaunchX a Sony XG9505 Android 9

### ISSUE THREAD

**Issue by pokurim** [codefaktor/FTVLaunchX#5]
Hello! I’ve installed FTVLauncherX on a Sony XG 9505 TV with Android 9 Pie for testing. The program works great by switching the original launcher to ATV Launcher Pro. There is only one feature: the volume control on the TV does not work when you hold the button. The volume increases or decreases by only one step per press. It doesn't matter which launcher I switch to. As soon as I activate FTVLauncherX, the volume control stops working properly. I understand that the program was not developed exactly for the Sony TV and Android 9, Is there any solution to the problem?

**Comment by ErikAbele** [comment]
I'm sorry to hear that but since I don't have access to a Sony XG 9505 TV I won't be able to investigate and maybe fix it.
