### ISSUE TITLE
restart it's worked but home button still back to amazon home

### ISSUE THREAD

**Issue by 7x11** [codefaktor/FTVLaunchX#7]
I use FTVlaunchX 3month maybe more . it's never happend  like this.
I'm not sure the FireTV4K's ver it's update? now it's 6.2.7.3

restart it's worked .
but home button still back to amazon home.
i try to install again.  can't fix it.

how to fix it?

tks.

**Comment by dadoremix** [comment]
amazaon via update has killed launcher
maybe dev have fix

**Comment by 7x11** [comment]
> amazaon via update has killed launcher
> maybe dev have fix

thanks

**Comment by ErikAbele** [comment]
Duplicate of #4 – closed.
