### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by ManuLinares** [codefaktor/FTVLaunchX#8]
https://github.com/codefaktor/FTVLaunchX/blame/develop/README.md#L207

should be 

`adb shell pm grant de.codefaktor.ftvlaunchx android.permission.WRITE_SECURE_SETTINGS`

**Comment by RubixSolver99** [comment]
Yep @ManuLinares is right.

**Comment by ErikAbele** [comment]
Aye, should be fixed now – thanks for reporting!
