### ISSUE TITLE
Still not working?

### ISSUE THREAD

**Issue by Leomm04** [codefaktor/FTVLaunchX#9]
After updating my Fire TV Stick 2 LaunchX stopped working.
Will there be a fix?

**Comment by yurividal** [comment]
6.2.7.3 broke this app again. we have to hope the dev is able to workarround it again.

**Comment by dadoremix** [comment]
yep, broken also on my fire 4k afer update :(
but, after reboot 1st time working and then after not

**Comment by MPenSol** [comment]
yep, i have the OS Version 6.2.7.3 too and it's not working. Hope for a workaround

**Comment by oathzed** [comment]
@codefaktor

**Comment by oathzed** [comment]
@ErikAbele

**Comment by RubixSolver99** [comment]
Yeah I'm running FireOS 5.2.7.4 on my Firestick 2nd Gen, and isn't working for me. Sadly, Amazon seemed to release another patch.

**Comment by ErikAbele** [comment]
Duplicate of #4 – closed.
